[project]
name = "icam-python"
version = "0.1.0"
description = "iCAM06 implementation in Python for image processing and chromatic adaptation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colour-science>=0.4.7",
    "matplotlib>=3.10.8",
    "numexpr>=2.14.1",
    "numpy>=2.4.1",
    "opencv-python>=4.13.0.90",
    "pillow>=12.1.0",
    "scipy>=1.17.0",
]
